Refactoring and simplification of postprocess
RAEL-Berkeley/switch pull request #110
Opened 2021-08-12 21:23 UTC by pesap

This PR refactors and simplify how we do the post-process for the `get_inputs` scripts.

In summary:
- Simplify `register_post_process` decorator to just include message.
- New argument on the `config.yaml` file that register which post process steps are wanted,
- Optional `post_process_step` argument that pass particular configuration for a given post_process (example below);
- Consisting naming for the main function of post_process_steps. Each script will have a `post_process` function that will be run if added to the configuration file.
- Using importlib to run the `post_process` function for each post process steps
- Changed `—post-process` to `—post-process-only` run all post process instead without query
-  New argument to the cli `—post-process-step` that will run just the given post process

Additional changes:
- Adds black format to all scripts
- Change wording of messages

2021-08-13 02:22 UTC, staadecker requested changes
I like this change! It makes everything a lot simpler. Could you update the template `config.yaml` in `switch_model.tools.templates` so that `switch new scenario` works properly? Other than that and my comments looks good

2021-08-13 02:22 UTC, staadecker commented on switch_model/wecc/get_inputs/post_process_steps/add_storage.py
>      name="add_storage",
So shouldn't this be removed as well as priority? There are a few post process steps that still have old properties.

2021-08-13 02:22 UTC, staadecker commented on switch_model/wecc/get_inputs/register_post_process.py
>      Decorator that should be used to register a post-processing step.
Remove param from docstring since outdated

2021-08-13 02:22 UTC, staadecker commented on switch_model/wecc/get_inputs/register_post_process.py
> -        priority=2
I'm guessing the intent is for the order to be determined by the order specified in the config file? If so, that makes sense to me.

2021-08-13 02:22 UTC, staadecker commented on switch_model/wecc/get_inputs/register_post_process.py
>  import functools
I don't think we need this one anymore

2021-08-13 02:22 UTC, staadecker commented on switch_model/wecc/get_inputs/cli.py
> +        post_process(full_config, post_config)
it would make sense to me to only pass the config for that step to the process simplyfing this to one argument only

2021-08-13 02:22 UTC, staadecker commented on switch_model/wecc/get_inputs/cli.py
> +        run_post_process(getattr(args, "post_process_step"))
It seems like we're not longer using the old post process method, can we delete it?

2021-09-13 23:05 UTC, staadecker commented
Another thing I've thought about is this would make the existing configuration files not backwards compatible... Not sure if there's a way to avoid that? Maybe we should add a `version` field in `config.yaml` and if the version is not 2 then we ask them to update or go back to the current version of switch that supports version 1 of the config...

2021-09-27 18:30 UTC, pesap commented
I am merging this change to incorporate the new way of adding post process

2021-09-27 18:31 UTC, merged